# Generated by Django 5.2.3 on 2025-07-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='proyectos/')),
                ('tecnologias', models.CharField(help_text='Tecnologías separadas por coma', max_length=200)),
                ('enlace', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
