# Generated by Django 5.2.3 on 2025-07-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total_visitas', models.IntegerField(default=0)),
                ('visitantes_unicos', models.IntegerField(default=0)),
                ('paginas_vistas', models.IntegerField(default=0)),
                ('tiempo_promedio_sitio', models.FloatField(default=0.0)),
                ('tasa_rebote', models.FloatField(default=0.0)),
                ('fuente_principal', models.CharField(blank=True, max_length=50)),
                ('pagina_mas_visitada', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Resumen Analytics',
                'verbose_name_plural': 'Resúmenes Analytics',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ContactoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('servicio_interes', models.CharField(blank=True, max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha_contacto', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-fecha_contacto'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('visitas_totales', models.IntegerField(default=0)),
                ('visitas_unicas', models.IntegerField(default=0)),
                ('paginas_vistas', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estadística Diaria',
                'verbose_name_plural': 'Estadísticas Diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PaginaVisitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('nombre_amigable', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('visitas_totales', models.IntegerField(default=0)),
                ('ultima_visita', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Página Visitada',
                'verbose_name_plural': 'Páginas Visitadas',
                'ordering': ['-visitas_totales'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True, null=True)),
                ('referrer_source', models.CharField(default='directo', max_length=50)),
                ('page_visited', models.CharField(default='/', max_length=255)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='adminpanel__timesta_968607_idx'), models.Index(fields=['ip_address', 'timestamp'], name='adminpanel__ip_addr_1cf23c_idx'), models.Index(fields=['referrer_source'], name='adminpanel__referre_b8bacd_idx'), models.Index(fields=['page_visited'], name='adminpanel__page_vi_604410_idx'), models.Index(fields=['country_code'], name='adminpanel__country_fc6c32_idx')],
            },
        ),
    ]
