# Generated by Django 5.2.3 on 2025-07-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.CharField(blank=True, help_text='Precio del servicio (opcional). Ej: "$999 pesos", "Desde $500", "Cotización"', max_length=100, null=True)),
                ('icono', models.CharField(blank=True, choices=[('fas fa-globe', '🌐 Páginas Web'), ('fas fa-code', '💻 Desarrollo'), ('fas fa-shopping-cart', '🛒 Ecommerce'), ('fas fa-envelope', '📧 Correos'), ('fas fa-server', '🖥️ Hosting'), ('fas fa-link', '🔗 Dominios'), ('fas fa-lock', '🔒 SSL'), ('fas fa-shield-alt', '🛡️ Seguridad'), ('fab fa-wordpress', '🟦 WordPress'), ('fab fa-woocommerce', '🟪 WooCommerce'), ('fas fa-cogs', '⚙️ Servicios'), ('fas fa-mobile-alt', '📱 Apps Móviles'), ('fas fa-database', '🗄️ Base de Datos'), ('fas fa-cloud', '☁️ Cloud'), ('fas fa-chart-line', '📊 Analytics'), ('fas fa-paint-brush', '🎨 Diseño'), ('fas fa-rocket', '🚀 Optimización'), ('fas fa-headset', '🎧 Soporte')], help_text='Selecciona un icono de FontAwesome o deja vacío para usar imagen personalizada', max_length=100)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen personalizada (opcional). Si se selecciona, se usará en lugar del icono de FontAwesome', null=True, upload_to='servicios/')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
    ]
