# Generated by Django 5.0.7 on 2025-07-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descripcion_corta',
            field=models.TextField(blank=True, help_text='Descripción corta para mostrar en el home (máximo 300 caracteres)', max_length=300),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(help_text='Descripción completa optimizada para SEO (para página de detalle)'),
        ),
    ]
