# Generated by Django 5.0.7 on 2025-07-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_descripcion_corta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='icono',
            field=models.CharField(blank=True, choices=[('fas fa-globe', '🌐 Páginas Web'), ('fas fa-code', '💻 Desarrollo'), ('fas fa-shopping-cart', '🛒 Ecommerce'), ('fas fa-envelope', '📧 Correos'), ('fas fa-server', '🖥️ Hosting'), ('fas fa-link', '🔗 Dominios'), ('fas fa-lock', '🔒 SSL'), ('fas fa-shield-alt', '🛡️ Seguridad'), ('fab fa-wordpress', '🟦 WordPress'), ('fab fa-woocommerce', '🟪 WooCommerce'), ('fas fa-cogs', '⚙️ Servicios'), ('fas fa-mobile-alt', '📱 Apps Móviles'), ('fas fa-database', '🗄️ Base de Datos'), ('fas fa-cloud', '☁️ Cloud'), ('fas fa-chart-line', '📊 Analytics'), ('fas fa-paint-brush', '🎨 Diseño'), ('fas fa-rocket', '🚀 Optimización'), ('fas fa-headset', '🎧 Soporte'), ('fas fa-search', '🔍 SEO'), ('fas fa-tools', '🔧 Mantenimiento'), ('fas fa-bullhorn', '📢 Marketing')], help_text='Selecciona un icono de FontAwesome o deja vacío para usar imagen personalizada', max_length=100),
        ),
    ]
