# Generated by Django 5.0.7 on 2025-07-04 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_purchasableservice_servicecategory_cart_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WompiConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Wompi Principal', max_length=100, verbose_name='Nombre de Configuración')),
                ('public_key', models.CharField(max_length=200, verbose_name='Clave Pública')),
                ('private_key', models.CharField(max_length=200, verbose_name='Clave Privada')),
                ('events_secret', models.CharField(blank=True, max_length=200, verbose_name='Secret de Eventos')),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='Modo Sandbox')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('success_url', models.URLField(blank=True, verbose_name='URL de Éxito')),
                ('failure_url', models.URLField(blank=True, verbose_name='URL de Fallo')),
                ('pending_url', models.URLField(blank=True, verbose_name='URL de Pendiente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Configuración de Wompi',
                'verbose_name_plural': 'Configuraciones de Wompi',
            },
        ),
        migrations.CreateModel(
            name='WompiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wompi_id', models.CharField(max_length=100, unique=True, verbose_name='ID de Wompi')),
                ('reference', models.CharField(max_length=100, verbose_name='Referencia')),
                ('amount_in_cents', models.BigIntegerField(verbose_name='Monto en Centavos')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('payment_method', models.CharField(choices=[('CARD', 'Tarjeta de Crédito/Débito'), ('NEQUI', 'Nequi'), ('PSE', 'PSE'), ('BANCOLOMBIA_TRANSFER', 'Transferencia Bancolombia'), ('BANCOLOMBIA_COLLECT', 'Botón Bancolombia')], max_length=30, verbose_name='Método de Pago')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('DECLINED', 'Rechazada'), ('VOIDED', 'Anulada'), ('ERROR', 'Error')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email del Cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Cliente')),
                ('redirect_url', models.URLField(blank=True, verbose_name='URL de Redirección')),
                ('wompi_response', models.JSONField(default=dict, verbose_name='Respuesta de Wompi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wompi_transaction', to='accounts.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Transacción de Wompi',
                'verbose_name_plural': 'Transacciones de Wompi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WompiWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True, verbose_name='ID del Evento')),
                ('event_type', models.CharField(choices=[('transaction.updated', 'Transacción Actualizada'), ('payment_link.paid', 'Enlace de Pago Pagado'), ('payment_source.created', 'Fuente de Pago Creada')], max_length=50, verbose_name='Tipo de Evento')),
                ('data', models.JSONField(verbose_name='Datos del Evento')),
                ('signature', models.TextField(verbose_name='Firma del Evento')),
                ('processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.wompitransaction', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Evento de Webhook Wompi',
                'verbose_name_plural': 'Eventos de Webhook Wompi',
                'ordering': ['-created_at'],
            },
        ),
    ]
