# Generated by Django 5.0.7 on 2025-07-04 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_wompiconfiguration_wompitransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_version', models.CharField(default='1.0', max_length=10, verbose_name='Versión de Términos')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Aceptación')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Aceptación de Términos',
                'verbose_name_plural': 'Aceptaciones de Términos',
                'ordering': ['-accepted_at'],
                'unique_together': {('user', 'terms_version')},
            },
        ),
    ]
