# Generated by Django 5.0.7 on 2025-07-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_termsacceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3, verbose_name='Moneda Origen')),
                ('to_currency', models.CharField(max_length=3, verbose_name='Moneda Destino')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Tasa de Cambio')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('source', models.CharField(default='exchangerate-api', max_length=50, verbose_name='Fuente')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-updated_at'],
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
