# Generated by Django 5.0.7 on 2025-07-04 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_exchangerate'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasableservice',
            options={'ordering': ['-is_featured', 'home_service', 'name'], 'verbose_name': 'Servicio Comprable', 'verbose_name_plural': 'Servicios Comprables'},
        ),
        migrations.RemoveField(
            model_name='purchasableservice',
            name='category',
        ),
        migrations.AddField(
            model_name='purchasableservice',
            name='home_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchasable_services', to='servicios.servicio', verbose_name='Servicio del Home'),
            preserve_default=False,
        ),
    ]
